Repository Junqo-org/junqo-platform, pull requests merged in 2025-02, with the labels that each got.

#79 Fix mirroring running on eip repository
  .github/workflows/eip-mirroring.yml
Labels: bug

#87 Connect front to back
  .gitignore
  db/test_data.sql
  docker-compose.dev.yaml
  docker-compose.yaml
  docs/developer/backend.md
  docs/developer/index.md
  junqo_back/dockerfile.dev
  junqo_back/dockerfile.prod
  junqo_back/exemple.env
  junqo_back/src/auth/auth.resolver.spec.ts
  junqo_back/src/auth/auth.resolver.ts
  junqo_back/src/auth/auth.service.ts
  junqo_back/src/main.ts
  junqo_back/test/app.e2e-spec.ts
  junqo_front/.gitignore
  junqo_front/lib/client.dart
  junqo_front/lib/core/auth_service.dart
  junqo_front/lib/core/client.dart
  junqo_front/lib/core/config.dart
  junqo_front/lib/main.dart
  junqo_front/lib/pages/cv.dart
  junqo_front/lib/pages/home_page.dart
  junqo_front/lib/pages/ia_page.dart
  junqo_front/lib/pages/interview.dart
  junqo_front/lib/pages/login.dart
  junqo_front/lib/pages/messaging_page.dart
  junqo_front/lib/pages/motivation.dart
  junqo_front/lib/pages/not_found_page.dart
  junqo_front/lib/pages/privacy_policy.dart
  junqo_front/lib/pages/profile_page.dart
  junqo_front/lib/pages/register.dart
  junqo_front/lib/pages/terms_of_use.dart
  junqo_front/lib/pages/user_type_selection.dart
  junqo_front/lib/pages/welcome.dart
  junqo_front/lib/router.dart
  junqo_front/lib/schemas/requests/is_logged_in.graphql
  junqo_front/lib/schemas/requests/sign_in.graphql
  junqo_front/lib/schemas/requests/sign_up.graphql
  junqo_front/lib/shared/dto/user_type.dart
  junqo_front/lib/shared/errors/graphql_exception.dart
  junqo_front/lib/shared/errors/show_error_dialog.dart
  junqo_front/lib/shared/theme.dart
  junqo_front/lib/shared/widgets/navbar.dart
  junqo_front/lib/shared/widgets/private_page.dart
  schemas/schema.graphql
  schemas/schema.graphql.planned
Labels: frontend, backend

#86 Add beta test plan
  beta_test_plan.md
  tools/fake_server.tmp.py
Labels: documentation

#89 Update front documentation
  .github/workflows/build-docker-images.yml
  docker-compose.dev.yaml
  docker-compose.yaml
  docs/developer/backend.md
  docs/developer/ci_cd.md
  docs/developer/frontend.md
  docs/developer/setup.md
  junqo_back/exemple.env
  junqo_front/config/exemple.env
  junqo_front/dockerfile.dev
  junqo_front/dockerfile.prod
  junqo_front/lib/core/auth_service.dart
  junqo_front/lib/core/config.dart
  junqo_front/lib/main.dart
  junqo_front/lib/pages/not_found_page.dart
  junqo_front/pubspec.lock
  junqo_front/pubspec.yaml
  tools/fake_server.tmp.py
  tools/update_schemas.py
Labels: documentation, enhancement, frontend

#90 Fix cors
  docs/developer/backend.md
  docs/developer/ci_cd.md
  junqo_back/exemple.env
  junqo_back/src/app.module.ts
  junqo_back/src/main.ts
Labels: bug, backend

#92 Jobcard and User card
  junqo_front/assets/images/image_placeholder.svg
  junqo_front/lib/pages/home_page.dart
  junqo_front/lib/pages/ia_page.dart
  junqo_front/lib/pages/interview.dart
  junqo_front/lib/pages/jobcard.dart
  junqo_front/lib/pages/messaging_page.dart
  junqo_front/lib/pages/motivation.dart
  junqo_front/lib/pages/offer_creation.dart
  junqo_front/lib/pages/profile_page.dart
  junqo_front/lib/pages/profile_recruter.dart
  junqo_front/lib/pages/profile_student.dart
  junqo_front/lib/pages/recruter_dashboard.dart
  junqo_front/lib/router.dart
  junqo_front/lib/shared/widgets/navbar.dart
Labels: enhancement, frontend

#95 Add release tagger action
  .github/workflows/back-tests.yml
  .github/workflows/deployment-tests.yml
  .github/workflows/front-tests.yml
  .github/workflows/pull-request-target-protection.yml
  .github/workflows/release-maker.yml
Labels: ci / cd

#100 Fix doc scalar
  .github/workflows/build-docker-images.yml
  magidoc.mjs
Labels: documentation, ci / cd

#102 Fix docker build action permissions
  .github/workflows/build-docker-images.yml
Labels: bug, ci / cd

#103 Update release maker to use pull request
  .github/workflows/release-maker.yml
Labels: ci / cd

#101 Realease v0.1.1
  .github/workflows/build-docker-images.yml
  .github/workflows/release-maker.yml
  magidoc.mjs
Labels: bug, documentation

#106 Update local actions
  docs/developer/ci_cd.md
  junqo_back/package-lock.json
  junqo_back/package.json
  tools/act-event-file.json
Labels: bug, documentation

#104 Notification
  junqo_front/lib/shared/widgets/navbar.dart
  junqo_front/lib/shared/widgets/notification.dart
  junqo_front/pubspec.lock
Labels: enhancement, frontend
