Repository Junqo-org/junqo-platform, pull requests merged in 2025-04, with the labels that each got.

#118 Update btp
  beta_test_plan.md
Labels: enhancement

#123 Refactor dev 1
  junqo_back/src/app.setup.ts
  junqo_back/src/applications/applications.controller.ts
  junqo_back/src/auth/auth.controller.ts
  junqo_back/src/casl/casl-ability.factory.spec.ts
  junqo_back/src/casl/casl-ability.factory.ts
  junqo_back/src/company-profiles/company-profiles.controller.ts
  junqo_back/src/experiences/experiences.module.ts
  junqo_back/src/experiences/repository/experiences.repository.module.ts
  junqo_back/src/experiences/repository/models/experience.model.ts
  junqo_back/src/offers/dto/offer.dto.ts
  junqo_back/src/offers/offers.controller.ts
  junqo_back/src/offers/offers.service.ts
  junqo_back/src/school-profiles/school-profiles.controller.ts
  junqo_back/src/student-profiles/dto/student-profile.dto.ts
  junqo_back/src/student-profiles/repository/student-profiles.repository.spec.ts
  junqo_back/src/student-profiles/repository/student-profiles.repository.ts
  junqo_back/src/student-profiles/student-profiles.controller.ts
  junqo_back/src/users/users.controller.ts
  junqo_back/test/applications.e2e-spec.ts
  junqo_back/test/offers.e2e-spec.ts
  junqo_back/test/studentProfiles.e2e-spec.ts
Labels: backend

#120 Front back profile connexion
  junqo_back/package-lock.json
  junqo_back/package.json
  junqo_front/flutter_01.png
  junqo_front/lib/core/api/api_service.dart
  junqo_front/lib/core/api/endpoints.dart
  junqo_front/lib/core/auth_service.dart
  junqo_front/lib/core/client.dart
  junqo_front/lib/core/company_profile_service.dart
  junqo_front/lib/core/student_profile_service.dart
  junqo_front/lib/main.dart
  junqo_front/lib/pages/home_page.dart
  junqo_front/lib/pages/jobcard.dart
  junqo_front/lib/pages/offer_creation.dart
  junqo_front/lib/pages/offer_list.dart
  junqo_front/lib/pages/profile_page.dart
  junqo_front/lib/pages/profile_recruter.dart
  junqo_front/lib/pages/profile_student.dart
  junqo_front/lib/services/offer_service.dart
  junqo_front/lib/shared/dto/company_profile.dart
  junqo_front/lib/shared/dto/student_profile.dart
Labels: frontend
